# Generated by Django 4.1.1 on 2022-10-22 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advocate',
            old_name='usernmae',
            new_name='username',
        ),
    ]
